supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc

onlyBuiltDependencies:
  - sharp

ignoredBuiltDependencies:
  - "@prisma/engines"
  - esbuild
  - prisma
  - unrs-resolver
